ignored:
  - DL3008 # Pin versions in apt get install
  - DL3018 # Pin versions in apk add
  - DL3013 # Pin versions in pip
  - DL3059 # Multiple consecutive RUN instructions
  - DL3015 # Avoid additional packages by specifying --no-install-recommends
