---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
  document-start:
    present: false
  truthy:
    allowed-values: ["true", "false", "on", "off"]

ignore: |
  .github/workflows/
  node_modules/
  venv/
  .venv/
  build/
  dist/
