global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "ai-discover"
    environment: "production"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/metrics"

  # Backend API metrics
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL exporter
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Redis exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Celery/Flower metrics
  - job_name: "celery"
    static_configs:
      - targets: ["flower:5555"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Docker metrics
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s
