name: Dependency Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-python-dependencies:
    name: Update Python Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update Python dependencies
        working-directory: backend
        run: |
          # Update requirements files
          pip-compile --upgrade requirements.in
          pip-compile --upgrade requirements-dev.in
          pip-compile --upgrade requirements-test.in

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update python dependencies"
          title: "chore: Update Python dependencies"
          body: |
            ## Python Dependency Updates

            This PR updates Python dependencies to their latest compatible versions.

            ### Checklist
            - [ ] All tests pass
            - [ ] No security vulnerabilities introduced
            - [ ] Application builds successfully
            - [ ] Manual testing completed

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-python-dependencies
          delete-branch: true
          labels: |
            dependencies
            python

  update-node-dependencies:
    name: Update Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Update npm dependencies
        working-directory: frontend
        run: |
          npm update
          npm audit fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update node dependencies"
          title: "chore: Update Node.js dependencies"
          body: |
            ## Node.js Dependency Updates

            This PR updates Node.js dependencies to their latest compatible versions.

            ### Checklist
            - [ ] All tests pass
            - [ ] No security vulnerabilities introduced
            - [ ] Application builds successfully
            - [ ] Manual testing completed

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-node-dependencies
          delete-branch: true
          labels: |
            dependencies
            javascript

  update-docker-base-images:
    name: Update Docker Base Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Dockerfile base images
        run: |
          # Update Python base image
          sed -i 's/FROM python:[0-9.]\+/FROM python:3.11/' backend/Dockerfile
          
          # Update Node base image
          sed -i 's/FROM node:[0-9.]\+/FROM node:18/' frontend/Dockerfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update docker base images"
          title: "chore: Update Docker base images"
          body: |
            ## Docker Base Image Updates

            This PR updates Docker base images to their latest versions.

            ### Checklist
            - [ ] Images build successfully
            - [ ] No compatibility issues
            - [ ] Security scan passes

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-docker-images
          delete-branch: true
          labels: |
            dependencies
            docker